# Generated by Django 6.0.2 on 2026-02-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_address_user_gender_user_name_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Admin', 'Admin')], default='Buyer', max_length=20),
        ),
    ]
