# Generated by Django 6.0.2 on 2026-03-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_review', 'Pending Review'), ('ai_scanning', 'AI Scanning'), ('live', 'Live'), ('sold', 'Sold'), ('rejected', 'Rejected'), ('unavailable', 'Unavailable')], default='pending', max_length=20),
        ),
    ]
