# Generated by Django 6.0.2 on 2026-03-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0002_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='previous_owners',
            field=models.IntegerField(default=0),
        ),
    ]
