# Generated by Django 6.0.2 on 2026-03-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0003_alter_inspectionreport_previous_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='razorpay_order_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='razorpay_signature',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('razorpay', 'Net Banking / UPI (Razorpay)')], default='cash', max_length=20),
        ),
    ]
